Parameters:
  ServiceName:
    Type: String
    Description: Name of the Service ECS

  ClusterName:
    Type: String
    Description: Name of the cluster ECS

  TaskDefinitionARN:
    Type: String
    Description: ARN of the task definition

  SchedulingStrategy:
    Type: String
    Description: The scheduling strategy to use for the service
    Default: REPLICA
  
  DesiredCount:
    Type: Number
    Description: The number of instantiations of the specified task definition to place and keep running in your service.

  LBContainerName:
    Type: String
    Description: The name of the container (as it appears in a container definition) to associate with the load balancer

  LBContainerPort:
    Type: Number
    Description: The port on the container to associate with the load balancer.
  
  LBTargetGroupArn:
    Type: String
    Description: The full Amazon Resource Name (ARN) of the Elastic Load Balancing target group or groups associated with a service or task set.
    
  SubnetIDs:
    Type: CommaDelimitedList
    Description: List Id's of the subnets
  
  SecurityGroupIDs:
    Type: CommaDelimitedList
    Description: List Id's of the security groupps 
    
Resources:
  ECSServiceFargate:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      PlatformVersion: LATEST
      TaskDefinition: !Ref TaskDefinitionARN
      SchedulingStrategy: !Ref SchedulingStrategy
      DesiredCount: !Ref DesiredCount
      LoadBalancers:
      - ContainerName: !Ref LBContainerName
        ContainerPort: !Ref LBContainerPort
        LoadBalancerName: !Ref AWS::NoValue
        TargetGroupArn: !Ref LBTargetGroupArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: !Ref SecurityGroupIDs
          Subnets: !Ref SubnetIDs
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      EnableECSManagedTags: true

Outputs:
  Name:
    Description: Name of the service
    Value: !GetAtt ECSServiceFargate.Name