Parameters:
  ClusterName:
    Type: String
    Description: Name of the cluster ECS
    
  SubnetIDs:
    Type: CommaDelimitedList
    Description: List Id's of the subnets
  
  SecurityGroupIDs:
    Type: CommaDelimitedList
    Description: List Id's of the security groupps 

Resources:
  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${StackFilesPath}/ecs/cluster.yml"
      Parameters:
        ClusterName: !Sub "${ProjectName}-cluster"
  
  Service:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${StackFilesPath}/ecs/service_fargate.yml"
      Parameters:
        ServiceName: !Sub "${ProjectName}-service-ecs"
        ClusterName: !GetAtt Cluster.Outputs.Name
        TaskDefinitionARN: !Ref TaskDefinitionARN 
        DesiredCount: 1
        LBContainerName: "${ProjectName}-container"
        LBContainerPort: 80
        LBTargetGroupArn: 
        SubnetIDs: !Ref SubnetIDs
        SecurityGroupIDs: !Ref SecurityGroupIDs

  AutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ProjectName, AutoScalingRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/aws-service-role/AWSApplicationAutoscalingECSServicePolicy'

  AutoScalingTarget:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${StackFilesPath}/ecs/autoscaling_target.yml"
      Parameters:
        MinCapacity: 1
        MaxCapacity: 3
        ResourceId: !Join ['', [service/, !GetAtt Cluster.Outputs.Name, !GetAtt Service.Outputs.Name]]
        RoleARN: !Ref AutoScalingRole

  AutoScalingPolicy:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${StackFilesPath}/ecs/autoscaling_policy.yml"
      Parameters:
        PolicyName: !Sub "${ProjectName}-policy-ecs"
        PolicyType: TargetTrackingScaling
        ResourceId: !Join ['', [service/, !GetAtt Cluster.Outputs.Name, !GetAtt Service.Outputs.Name]]
        ScalingTargetId: !GetAtt AutoScalingTarget.Outputs.Id
        DisableScaleIn: false #### AGREGAR AL TEMPLATE
        ScaleInCooldown: 300
        ScaleOutCooldown: 300
        TargetValue: 80
        MetricType: ECSServiceAverageCPUUtilization